name: jlab
channels:
- conda-forge
- defaults
dependencies:
- bleach=2.0.0=py36_0
- certifi=2017.11.5=py36_0
- colorama=0.3.9=py36_0
- decorator=4.1.2=py36_0
- entrypoints=0.2.3=py36_1
- html5lib=1.0.1=py_0
- ipykernel=4.7.0=py36_0
- ipython=6.2.1=py36_1
- ipython_genutils=0.2.0=py36_0
- jedi=0.11.1=py36_0
- jinja2=2.10=py36_0
- jsonschema=2.5.1=py36_0
- jupyter_client=5.2.2=py36_0
- jupyter_core=4.4.0=py_0
- jupyterlab=0.31.2=py36_0
- jupyterlab_launcher=0.10.3=py36_0
- markupsafe=1.0=py36_0
- mistune=0.8.3=py_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py36_0
- notebook=5.4.0=py36_0
- pandoc=2.1.1=0
- pandocfilters=1.4.1=py36_0
- parso=0.1.1=py_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.15=py36_0
- pygments=2.2.0=py36_0
- python=3.6.4=0
- python-dateutil=2.6.1=py36_0
- pywinpty=0.5=py36_0
- pyzmq=16.0.2=py36_3
- send2trash=1.4.2=py_0
- setuptools=38.4.0=py36_0
- simplegeneric=0.8.1=py36_0
- six=1.11.0=py36_1
- terminado=0.8.1=py36_0
- testpath=0.3.1=py36_0
- tornado=4.5.3=py36_0
- traitlets=4.3.2=py36_0
- vc=14=0
- vs2015_runtime=14.0.25420=0
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- wheel=0.30.0=py36_2
- wincertstore=0.2=py36_0
- winpty=0.4.3=vc14_2
- cycler=0.10.0=py36_0
- icu=57.1=vc14_0
- jpeg=9b=vc14_0
- libpng=1.6.30=vc14_1
- matplotlib=2.0.2=np113py36_0
- mkl=2017.0.3=0
- numpy=1.13.1=py36_0
- openssl=1.0.2l=vc14_0
- pandas=0.20.3=py36_0
- pyodbc=4.0.17=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_2
- pytz=2017.2=py36_0
- qt=5.6.2=vc14_6
- sip=4.18=py36_0
- tk=8.5.18=vc14_0
- zlib=1.2.11=vc14_0
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.2
  - jupyter-core==4.4.0
  - jupyterlab-launcher==0.10.3
  - prompt-toolkit==1.0.15
